const Router = require("express");
const router = new Router();

const etudiantRoutes = require("./etudianttRoutes/etudiantRoutes");
const classeRoutes = require("./classeRoutes/classeRoutes");
const parentRoutes = require("./parentRoutes/parentRoutes");
const observationRoutes = require("./observationRoutes/observationRoutes");
const centralAppRoutes = require("./centralAppRoutes/centralAppRoutes");
const enseignantRoutes = require("./enseignantRoutes/enseignantRoutes");
const exerciceRoutes = require("./exerciceRoutes/exerciceRoutes");
const disciplineRoutes = require("./disciplineRoutes/disciplineRoutes");
const emploiRoutes = require("./emploiRoutes/emploiRoutes");
const matiereRoutes = require("./matiereRoutes/matiereRoutes");
const noteRoutes = require("./noteRoutes/noteRoutes");
const carnetRoutes = require("./carnetRoutes/carnetRoutes");
const absenceRoutes = require("./absenceRoutes/absenceRoutes");
const avisRoutes = require("./avisRoutes/avisRoutes");
const documentRoutes = require("./documentRoutes/documentRoutes");
const evenementRoutes = require("./evenementRoutes/evenementRoutes");
const compteRenduRoutes = require("./compteRenduRoutes/compteRenduRoutes");
const gallerieRoutes = require("./gallerieRoutes/gallerieRoutes");
const messagerieRoutes = require("./msgRoutes/msgRoutes");
const cantineRoutes = require("./cantineRoutes/cantineRoutes");
const paiementRoutes = require("./paiementRoutes/paiementRoutes");
const salleRoutes = require("./salleRoutes/salleRoutes");
const calendrierRoutes = require("./calendrierRoutes/calendrierRoutes");
const evaluationRoutes = require("./evaluationRoutes/evaluationsRoutes");
const rendezvousRoutes = require("./rendezvousRoutes/rendezvousRoutes");
const notificationRoutes = require("./notificationRoutes/notificationRoutes");
const inscriptionRoutes = require("./inscriptionRoutes/inscriptionRoutes");
const niveauRoutes = require("./niveauRoutes/niveauRoutes");
const smsRoutes = require("./smsRoutes/smsRoutes");

router.use("/etudiants", etudiantRoutes);
router.use("/classes", classeRoutes);
router.use("/parents", parentRoutes);
router.use("/observations", observationRoutes);
router.use("/central", centralAppRoutes);
router.use("/enseignants", enseignantRoutes);
router.use("/exercices", exerciceRoutes);
router.use("/disciplines", disciplineRoutes);
router.use("/emplois", emploiRoutes);
router.use("/matieres", matiereRoutes);
router.use("/notes", noteRoutes);
router.use("/carnets", carnetRoutes);
router.use("/absences", absenceRoutes);
router.use("/avis", avisRoutes);
router.use("/documents", documentRoutes);
router.use("/evenements", evenementRoutes);
router.use("/compteRendus", compteRenduRoutes);
router.use("/galleries", gallerieRoutes);
router.use("/messages", messagerieRoutes);
router.use("/cantines", cantineRoutes);
router.use("/paiements", paiementRoutes);
router.use("/salles", salleRoutes);
router.use("/calendriers", calendrierRoutes);
router.use("/evaluations", evaluationRoutes);
router.use("/rendez-vous", rendezvousRoutes);
router.use("/notifications", notificationRoutes);
router.use("/inscriptions", inscriptionRoutes);
router.use("/niveaux", niveauRoutes);
router.use("/msgSms", smsRoutes);

module.exports = router;
